# Generated by Django 5.2.5 on 2025-08-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QY', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFOCRData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_path', models.CharField(max_length=1024, verbose_name='文件地址')),
                ('personal_history', models.TextField(blank=True, null=True, verbose_name='个人史')),
                ('chief_complaint', models.TextField(blank=True, null=True, verbose_name='主诉')),
                ('inpatient_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='住院号')),
                ('admission_status', models.TextField(blank=True, null=True, verbose_name='入院情况')),
                ('admission_diagnosis', models.TextField(blank=True, null=True, verbose_name='入院诊断')),
                ('discharge_diagnosis', models.TextField(blank=True, null=True, verbose_name='出院诊断')),
                ('marital_history', models.TextField(blank=True, null=True, verbose_name='婚姻史')),
                ('family_history', models.TextField(blank=True, null=True, verbose_name='家族史')),
                ('imaging_opinion', models.TextField(blank=True, null=True, verbose_name='影像学意见')),
                ('operation_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='手术名称')),
                ('operation_course', models.TextField(blank=True, null=True, verbose_name='手术经过')),
                ('past_history', models.TextField(blank=True, null=True, verbose_name='既往史')),
                ('intraoperative_diagnosis', models.TextField(blank=True, null=True, verbose_name='术中诊断')),
                ('present_illness', models.TextField(blank=True, null=True, verbose_name='现病史')),
                ('case_identifier', models.CharField(blank=True, max_length=255, null=True, verbose_name='病案标识')),
                ('course_record', models.TextField(blank=True, null=True, verbose_name='病程记录')),
                ('treatment_course', models.TextField(blank=True, null=True, verbose_name='诊疗经过')),
                ('ultrasound_impression', models.TextField(blank=True, null=True, verbose_name='超声印象')),
                ('ultrasound_hint', models.TextField(blank=True, null=True, verbose_name='超声提示')),
            ],
            options={
                'verbose_name': 'PDF OCR 数据',
                'verbose_name_plural': 'PDF OCR 数据',
            },
        ),
    ]
