# Generated by Django 5.2.5 on 2025-08-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QY', '0002_pdfocrdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfocrdata',
            name='raw_text',
            field=models.TextField(blank=True, null=True, verbose_name='原始文本'),
        ),
    ]
