# Generated by Django 5.2.8 on 2025-11-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QY', '0004_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diag_seq', models.IntegerField(verbose_name='诊断序号')),
                ('diag_type', models.CharField(max_length=50, verbose_name='诊断类型')),
                ('diag_code', models.CharField(max_length=50, verbose_name='诊断编码')),
                ('diag_name', models.CharField(max_length=200, verbose_name='诊断名称')),
            ],
            options={
                'verbose_name': '诊断',
                'verbose_name_plural': '诊断',
            },
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_seq', models.IntegerField(verbose_name='手术序号')),
                ('surgery_code', models.CharField(max_length=50, verbose_name='手术编码')),
                ('surgery_name', models.CharField(max_length=200, verbose_name='手术名称')),
            ],
            options={
                'verbose_name': '手术',
                'verbose_name_plural': '手术',
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
