# Generated by Django 5.2.8 on 2025-11-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QY', '0005_diagnosis_surgery_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_Patient_Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(help_text='住院号/病案号', max_length=50, verbose_name='病案标识号')),
                ('diag_type', models.CharField(choices=[('出院诊断', '出院诊断'), ('损伤中毒', '损伤中毒'), ('病理诊断', '病理诊断')], help_text='枚举：出院诊断 / 损伤中毒 / 病理诊断', max_length=20, verbose_name='诊断类型')),
                ('diag_seq', models.IntegerField(help_text='诊断顺序号，主诊断=1', verbose_name='诊断序号')),
                ('diag_code', models.CharField(help_text='关联诊断编码字典库', max_length=50, verbose_name='诊断编码')),
                ('diag_name', models.CharField(help_text='关联诊断名称字典库', max_length=200, verbose_name='诊断名称')),
            ],
            options={
                'verbose_name': '诊断',
                'verbose_name_plural': '诊断',
                'ordering': ['case_id', 'diag_type', 'diag_seq'],
            },
        ),
        migrations.CreateModel(
            name='V_Patient_Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(help_text='住院号/病案号', max_length=50, verbose_name='病案标识号')),
                ('surgery_seq', models.IntegerField(help_text='手术顺序号，主手术为1', verbose_name='手术序号')),
                ('surgery_code', models.CharField(help_text='关联手术编码字典库', max_length=50, verbose_name='手术编码')),
                ('surgery_name', models.CharField(help_text='关联手术名称字典库', max_length=200, verbose_name='手术名称')),
            ],
            options={
                'verbose_name': '手术',
                'verbose_name_plural': '手术',
                'ordering': ['case_id', 'surgery_seq', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
        migrations.DeleteModel(
            name='Surgery',
        ),
    ]
