# Generated by Django 5.2.8 on 2025-12-16 04:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QY', '0008_chathistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSessions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='侧边栏标题 (支持自动生成或手动修改)', max_length=255, null=True, verbose_name='会话标题')),
                ('chat_mode', models.CharField(choices=[('coding', 'Coding'), ('knowledge', 'Knowledge')], default='knowledge', help_text='消息类型：coding 或者 knowledge', max_length=20, verbose_name='消息类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后活跃时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '聊天会话',
                'verbose_name_plural': '聊天会话',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_order', models.IntegerField(help_text='一次会话中的所有消息序号', verbose_name='消息序号')),
                ('message', models.JSONField(help_text='消息正文，一个content表示一个完整的消息', verbose_name='消息正文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='QY.chatsessions', verbose_name='所属会话')),
            ],
            options={
                'verbose_name': '会话消息',
                'verbose_name_plural': '会话消息',
                'ordering': ['session', 'message_order'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.IntegerField(help_text='某条消息中的诊断、手术数据行id', verbose_name='数据行ID')),
                ('type', models.CharField(choices=[('like', '点赞'), ('dislike', '点踩')], help_text='对于此数据行的反馈类型：like 或者 dislike', max_length=20, verbose_name='反馈类型')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='反馈内容')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='反馈时间')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='QY.chatmessages', verbose_name='关联消息')),
            ],
            options={
                'verbose_name': '消息反馈',
                'verbose_name_plural': '消息反馈',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
