# Generated by Django 5.2.9 on 2025-12-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QY", "0009_chatsessions_chatmessages_feedback_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="category",
            field=models.IntegerField(
                choices=[(0, "诊断"), (1, "手术")],
                default=0,
                help_text="0表示诊断、1表示手术",
                verbose_name="目标类型",
            ),
        ),
    ]
