# Generated by Django 5.2.9 on 2025-12-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QY', '0010_feedback_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='v_patient_diagnosis',
            name='model_response_time',
            field=models.DateTimeField(blank=True, help_text='记录模型生成该回复的时间点', null=True, verbose_name='模型回复时间'),
        ),
        migrations.AddField(
            model_name='v_patient_surgery',
            name='model_response_time',
            field=models.DateTimeField(blank=True, help_text='记录模型生成该回复的时间点', null=True, verbose_name='模型回复时间'),
        ),
    ]
