# Generated by Django 5.2.9 on 2026-01-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QY', '0011_v_patient_diagnosis_model_response_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='反馈类型'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.IntegerField(choices=[(0, '诊断'), (1, '手术')], default=0, help_text='0表示诊断、1表示手术', verbose_name='目标类别'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('like', '点赞'), ('dislike', '点踩')], help_text='对于此数据行的反馈类型：like 或者 dislike', max_length=20, verbose_name='反馈类别'),
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('message', 'category', 'row_id')},
        ),
    ]
