# Generated by Django 5.2.9 on 2026-01-10 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QY', '0013_alter_feedback_category_alter_feedback_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='reason',
        ),
    ]
