# Generated by Django 5.2.9 on 2026-01-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QY', '0014_remove_feedback_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='反馈标签'),
        ),
    ]
