# Generated by Django 5.2.9 on 2026-01-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QY', '0015_feedback_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('like', '点赞'), ('dislike', '点踩'), ('comment', '总体评价')], help_text='对于此数据行的反馈类型：like 或者 dislike', max_length=20, verbose_name='反馈类型'),
        ),
    ]
