# Generated by Django 5.2.9 on 2026-01-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QY', '0016_alter_feedback_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='isCollapsed',
            field=models.BooleanField(default=False, help_text='标记该消息在前端是否为折叠状态', verbose_name='折叠状态'),
        ),
        migrations.AddField(
            model_name='chatmessages',
            name='isFinished',
            field=models.BooleanField(default=False, help_text='标记用户是否已处理完成该消息', verbose_name='处理完成标记'),
        ),
    ]
