# Generated by Django 6.0.2 on 2026-02-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QY', '0017_chatmessages_iscollapsed_chatmessages_isfinished'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsessions',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='逻辑删除标记，True表示用户端已删除，但数据保留', verbose_name='是否删除'),
        ),
    ]
